import numpy as np
import pylab as py
import atpy
from jlu.hst import starlists
import math

scale = {'WFC': 0.050,
         'WFC3-IR': 0.130}

def plot_errors_wfc3ir(ks2Data, filterIndex, filterName,
                       minMagGood=-13.5, maxMagGood=-7
                       ):
    """
    Load up a ks2 data table and plot the astrometric errors for the designated filter.

    ks2Data - a FITS files name or an already loaded ATpy table. This table should
    have been generated by jlu.hst.starlists.read_ks2_avg_uv().

    filterIndex - 1-based index of the filter to use in plotting.
    """

    if type(ks2Data) == 'str':
        data = atpy.Table(ks2Data)
    else:
        data = ks2Data

    # Fetch out the info for the appropriate filter.
    x = data['x_%d' % filterIndex]
    y = data['y_%d' % filterIndex]
    m = data['m_%d' % filterIndex]
    xe = data['xe_%d' % filterIndex]
    ye = data['ye_%d' % filterIndex]
    me = data['me_%d' % filterIndex]
    
    # Photometric errors
    py.figure(1)
    py.clf()
    py.semilogy(m, me, 'k.', ms=2)
    py.xlabel('Instrumental Magnitude')
    py.ylabel('Photometric RMS Error (mag)')
    py.ylim(0.001, 1)
    py.xlim(-14, 0)
    py.title(filterName)
    py.savefig('plot_mag_err_%s.png' % filterName)

    # Astrometric errors
    py.figure(2)
    py.clf()
    py.semilogy(m, xe, 'r.', label='X', ms=2)
    py.semilogy(m, ye, 'b.', label='Y', ms=2)
    py.xlabel('Instrumental Magnitude')
    py.ylabel('Astrometric RMS Error (pix)')
    py.ylim(0.001, 1)
    py.xlim(-14, 0)
    py.title(filterName)
    py.legend(loc='upper left', numpoints=1)
    py.savefig('plot_pos_err_%s.png' % filterName)

    # Lets get the median errors inside the acceptable range.
    tabTrim = data.where((m > minMagGood) & (m < maxMagGood))
    xerr = np.median(tabTrim['xe_%d' % filterIndex])
    yerr = np.median(tabTrim['ye_%d' % filterIndex])
    merr = np.median(tabTrim['me_%d' % filterIndex])

    print 'Median Errors for Stars Between [%.1f, %.1f] for %s' % \
        (minMagGood, maxMagGood, filterName)
    print '     Photometric Error: %.2f mag' % (merr)
    print '   X Astrometric Error: %.3f pix' % (xerr)
    print '   Y Astrometric Error: %.3f pix' % (yerr)
